# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Check pm2 and node version
        run: |
          pm2 -v
          node -v

      # - run: |
      #     echo "Kill all the running PM2 actions"
      #     sudo pm2 kill
      #     echo "Start the PM2 action"
      # - run: |
      #     echo "Git pull the latest code"
      #     git pull
      # - run: |
      #     echo "Install the dependencies"
      #     sudo rm -rf node_modules package-lock.json
      #     sudo npm install
      # - run: |
      #     echo "Start the PM2 action"
      #     sudo pm2 start ecosystem.config.js --name "nodejs-app"
      # - run: |
      #     echo "Save the PM2 action"
      #     sudo pm2 save
      # - run: ls -la
      # - run: echo $PWD
      # - run: sudo pm2 list
      # - run: sudo pm2 logs nodejs-app
      # - run: sudo pm2 status nodejs-app

  # start:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm run start --if-present
