# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check pm2 and node version
        run: |
          pm2 -v
          node -v

      - name: 'Kill all running pm2 processes'
        run: pm2 kill

      - name: 'Git pull the latest code'
        run: git pull

      - name: 'Install the dependencies'
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: 'Start the PM2 action'
        run: pm2 start ecosystem.config.js --name "nodejs-app"

      - name: 'Save the PM2 action'
        run: pm2 save

      - run: ls -la
      - run: echo $PWD
      - run: pm2 list
      - run: pm2 logs nodejs-app
      - run: pm2 status nodejs-app

  # start:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm run start --if-present
